export const ACCOUNT_GROUPS = {
    // This is the central mapping of account numbers to their financial statement categories.
    // --- Fallback Handlers (by Class) ---
    '0': { type: 'A', category: 'assets_other_fixed' }, 
    '1': { type: 'A', category: 'assets_other_inventory' }, 
    '2': { type: 'A', category: 'assets_other_financial' }, 
    '3': { type: 'A', category: 'assets_other_receivables' }, 
    '4': { type: 'P', category: 'liabilities_other_equity' }, 
    '5': { type: 'N', category: 'costs_other', taxable: true }, 
    '6': { type: 'VYN', category: 'revenue_other', taxable: true },
    '7': { type: 'Z', category: 'closing_accounts' },
    
    // --- ÚČTOVÁ TRIEDA 0 - DLHODOBÝ MAJETOK ---
    '012': { type: 'A', category: 'fixed_assets_intangible' },
    '013': { type: 'A', category: 'fixed_assets_intangible' },
    '014': { type: 'A', category: 'fixed_assets_intangible' },
    '015': { type: 'V', assetCat: 'fixed_assets_intangible', liabilityCat: 'liabilities_other_long_term' },
    '019': { type: 'A', category: 'fixed_assets_intangible' },
    '021': { type: 'A', category: 'fixed_assets_tangible_depreciated' },
    '022': { type: 'A', category: 'fixed_assets_tangible_depreciated' },
    '025': { type: 'A', category: 'fixed_assets_tangible_depreciated' },
    '026': { type: 'A', category: 'fixed_assets_tangible_depreciated' },
    '029': { type: 'A', category: 'fixed_assets_tangible_depreciated' },
    '031': { type: 'A', category: 'fixed_assets_tangible_non_depreciated' },
    '032': { type: 'A', category: 'fixed_assets_tangible_non_depreciated' },
    '041': { type: 'A', category: 'fixed_assets_in_progress' },
    '042': { type: 'A', category: 'fixed_assets_in_progress' },
    '043': { type: 'A', category: 'fixed_assets_in_progress' },
    '051': { type: 'A', category: 'fixed_assets_advances' },
    '052': { type: 'A', category: 'fixed_assets_advances' },
    '053': { type: 'A', category: 'fixed_assets_advances' },
    '061': { type: 'A', category: 'fixed_assets_financial' },
    '062': { type: 'A', category: 'fixed_assets_financial' },
    '063': { type: 'A', category: 'fixed_assets_financial' },
    '065': { type: 'A', category: 'fixed_assets_financial' },
    '066': { type: 'A', category: 'fixed_assets_financial' },
    '067': { type: 'A', category: 'fixed_assets_financial' },
    '069': { type: 'A', category: 'fixed_assets_financial' },
    '072': { type: 'P', category: 'corrections_depreciation_intangible' },
    '073': { type: 'P', category: 'corrections_depreciation_intangible' },
    '074': { type: 'P', category: 'corrections_depreciation_intangible' },
    '075': { type: 'V', assetCat: 'fixed_assets_intangible', liabilityCat: 'corrections_depreciation_intangible' },
    '079': { type: 'P', category: 'corrections_depreciation_intangible' },
    '081': { type: 'P', category: 'corrections_depreciation_tangible' },
    '082': { type: 'P', category: 'corrections_depreciation_tangible' },
    '085': { type: 'P', category: 'corrections_depreciation_tangible' },
    '086': { type: 'P', category: 'corrections_depreciation_tangible' },
    '089': { type: 'P', category: 'corrections_depreciation_tangible' },
    '091': { type: 'P', category: 'corrections_impairment_fixed' },
    '092': { type: 'P', category: 'corrections_impairment_fixed' },
    '093': { type: 'P', category: 'corrections_impairment_fixed' },
    '094': { type: 'P', category: 'corrections_impairment_fixed' },
    '095': { type: 'P', category: 'corrections_impairment_fixed' },
    '096': { type: 'P', category: 'corrections_impairment_fixed' },
    '097': { type: 'V', assetCat: 'corrections_impairment_fixed', liabilityCat: 'liabilities_other_long_term' },
    '098': { type: 'V', assetCat: 'corrections_impairment_fixed', liabilityCat: 'liabilities_other_long_term' },
    '111': { type: 'A', category: 'inventory_material' },
    '112': { type: 'A', category: 'inventory_material' },
    '119': { type: 'A', category: 'inventory_material' },
    '121': { type: 'A', category: 'inventory_own_production' },
    '122': { type: 'A', category: 'inventory_own_production' },
    '123': { type: 'A', category: 'inventory_own_production' },
    '124': { type: 'A', category: 'inventory_own_production' },
    '131': { type: 'A', category: 'inventory_goods' },
    '132': { type: 'A', category: 'inventory_goods' },
    '133': { type: 'A', category: 'inventory_goods' },
    '139': { type: 'A', category: 'inventory_goods' },
    '191': { type: 'P', category: 'corrections_impairment_inventory' },
    '192': { type: 'P', category: 'corrections_impairment_inventory' },
    '193': { type: 'P', category: 'corrections_impairment_inventory' },
    '194': { type: 'P', category: 'corrections_impairment_inventory' },
    '195': { type: 'P', category: 'corrections_impairment_inventory' },
    '196': { type: 'P', category: 'corrections_impairment_inventory' },
    '211': { type: 'A', category: 'financial_cash' },
    '213': { type: 'A', category: 'financial_cash' },
    '221': { type: 'V', assetCat: 'financial_bank', liabilityCat: 'liabilities_bank_loans_short_term' },
    '222': { type: 'A', category: 'financial_bank' },
    '223': { type: 'A', category: 'financial_bank' },
    '231': { type: 'P', category: 'liabilities_bank_loans_short_term' },
    '232': { type: 'P', category: 'liabilities_bank_loans_short_term' },
    '241': { type: 'P', category: 'liabilities_bank_loans_short_term' },
    '249': { type: 'P', category: 'liabilities_bank_loans_short_term' },
    '251': { type: 'A', category: 'financial_short_term_assets' },
    '252': { type: 'A', category: 'financial_short_term_assets' },
    '253': { type: 'A', category: 'financial_short_term_assets' },
    '255': { type: 'A', category: 'financial_short_term_assets' },
    '256': { type: 'A', category: 'financial_short_term_assets' },
    '257': { type: 'A', category: 'financial_short_term_assets' },
    '258': { type: 'A', category: 'financial_short_term_assets' },
    '259': { type: 'A', category: 'financial_short_term_assets' },
    '261': { type: 'V', assetCat: 'financial_transfers', liabilityCat: 'financial_transfers' },
    '291': { type: 'P', category: 'corrections_impairment_financial_short_term' },
    '311': { type: 'A', category: 'receivables_trade' },
    '312': { type: 'A', category: 'receivables_trade' },
    '313': { type: 'A', category: 'receivables_trade' },
    '314': { type: 'A', category: 'receivables_trade' },
    '315': { type: 'A', category: 'receivables_other' },
    '316': { type: 'V', assetCat: 'receivables_trade', liabilityCat: 'liabilities_trade' },
    '318': { type: 'A', category: 'receivables_state_taxes' },
    '321': { type: 'P', category: 'liabilities_trade' },
    '322': { type: 'P', category: 'liabilities_trade' },
    '323': { type: 'P', category: 'liabilities_reserves_short_term' },
    '324': { type: 'P', category: 'liabilities_trade' },
    '325': { type: 'P', category: 'liabilities_other' },
    '326': { type: 'P', category: 'liabilities_trade' },
    '331': { type: 'P', category: 'liabilities_employees_social' },
    '333': { type: 'P', category: 'liabilities_employees_social' },
    '335': { type: 'A', category: 'receivables_employees_social' },
    '336': { type: 'V', assetCat: 'receivables_employees_social', liabilityCat: 'liabilities_employees_social' },
    '341': { type: 'V', assetCat: 'receivables_state_taxes', liabilityCat: 'liabilities_state_taxes' },
    '342': { type: 'V', assetCat: 'receivables_state_taxes', liabilityCat: 'liabilities_state_taxes' },
    '343': { type: 'V', assetCat: 'receivables_state_taxes', liabilityCat: 'liabilities_state_taxes' },
    '345': { type: 'V', assetCat: 'receivables_state_taxes', liabilityCat: 'liabilities_state_taxes' },
    '346': { type: 'V', assetCat: 'receivables_state_subsidies', liabilityCat: 'liabilities_state_subsidies' },
    '347': { type: 'V', assetCat: 'receivables_state_subsidies', liabilityCat: 'liabilities_state_subsidies' },
    '348': { type: 'V', assetCat: 'receivables_state_subsidies', liabilityCat: 'liabilities_state_subsidies' },
    '351': { type: 'A', category: 'receivables_partners' },
    '353': { type: 'A', category: 'receivables_partners' },
    '354': { type: 'A', category: 'receivables_partners' },
    '355': { type: 'A', category: 'receivables_partners' },
    '357': { type: 'A', category: 'receivables_partners' },
    '358': { type: 'A', category: 'receivables_partners' },
    '361': { type: 'P', category: 'liabilities_partners' },
    '364': { type: 'P', category: 'liabilities_partners' },
    '365': { type: 'P', category: 'liabilities_partners' },
    '366': { type: 'P', category: 'liabilities_partners' },
    '367': { type: 'P', category: 'liabilities_partners' },
    '368': { type: 'P', category: 'liabilities_partners' },
    '371': { type: 'A', category: 'receivables_other' },
    '372': { type: 'P', category: 'liabilities_other' },
    '373': { type: 'V', assetCat: 'receivables_other', liabilityCat: 'liabilities_other' },
    '374': { type: 'A', category: 'receivables_other' },
    '375': { type: 'A', category: 'receivables_other' },
    '376': { type: 'A', category: 'receivables_other' },
    '377': { type: 'P', category: 'liabilities_other' },
    '378': { type: 'A', category: 'receivables_other' },
    '379': { type: 'P', category: 'liabilities_other' },
    '381': { type: 'A', category: 'accruals_assets' },
    '382': { type: 'A', category: 'accruals_assets' },
    '383': { type: 'P', category: 'accruals_liabilities' },
    '384': { type: 'P', category: 'accruals_liabilities' },
    '385': { type: 'A', category: 'accruals_assets' },
    '391': { type: 'P', category: 'corrections_impairment_receivables' },
    '395': { type: 'A', category: 'accruals_assets' },
    '398': { type: 'V', assetCat: 'receivables_other', liabilityCat: 'liabilities_other' },
    '411': { type: 'P', category: 'equity_base_capital_funds' },
    '412': { type: 'P', category: 'equity_base_capital_funds' },
    '413': { type: 'P', category: 'equity_base_capital_funds' },
    '414': { type: 'V', assetCat: 'equity_base_capital_funds', liabilityCat: 'equity_base_capital_funds' },
    '415': { type: 'V', assetCat: 'equity_base_capital_funds', liabilityCat: 'equity_base_capital_funds' },
    '416': { type: 'P', category: 'equity_base_capital_funds' },
    '417': { type: 'P', category: 'equity_base_capital_funds' },
    '418': { type: 'P', category: 'equity_base_capital_funds' },
    '419': { type: 'V', assetCat: 'equity_base_capital_funds', liabilityCat: 'equity_base_capital_funds' },
    '421': { type: 'P', category: 'equity_retained_earnings_funds' },
    '422': { type: 'P', category: 'equity_retained_earnings_funds' },
    '423': { type: 'P', category: 'equity_retained_earnings_funds' },
    '427': { type: 'P', category: 'equity_retained_earnings_funds' },
    '428': { type: 'P', category: 'equity_retained_earnings_funds' },
    '429': { type: 'P', category: 'equity_retained_earnings_funds' },
    '431': { type: 'V', assetCat: 'equity_profit_loss', liabilityCat: 'equity_profit_loss' },
    '451': { type: 'P', category: 'liabilities_reserves' },
    '459': { type: 'P', category: 'liabilities_reserves' },
    '461': { type: 'P', category: 'liabilities_bank_loans_long_term' },
    '471': { type: 'P', category: 'liabilities_other_long_term' },
    '472': { type: 'P', category: 'liabilities_other_long_term' },
    '473': { type: 'P', category: 'liabilities_other_long_term' },
    '474': { type: 'P', category: 'liabilities_other_long_term' },
    '475': { type: 'P', category: 'liabilities_other_long_term' },
    '476': { type: 'P', category: 'liabilities_other_long_term' },
    '478': { type: 'P', category: 'liabilities_other_long_term' },
    '479': { type: 'P', category: 'liabilities_other_long_term' },
    '481': { type: 'V', assetCat: 'receivables_deferred_tax', liabilityCat: 'liabilities_deferred_tax' },
    '491': { type: 'V', assetCat: 'equity_individual', liabilityCat: 'equity_individual' },
    '501': { type: 'N', category: 'costs_consumed_purchases', taxable: true },
    '502': { type: 'N', category: 'costs_consumed_purchases', taxable: true },
    '503': { type: 'N', category: 'costs_consumed_purchases', taxable: true },
    '504': { type: 'N', category: 'costs_consumed_purchases', taxable: true },
    '505': { type: 'N', category: 'costs_consumed_purchases', taxable: true },
    '507': { type: 'N', category: 'costs_consumed_purchases', taxable: true },
    '511': { type: 'N', category: 'costs_services', taxable: true },
    '512': { type: 'N', category: 'costs_services', taxable: true },
    '513': { type: 'N', category: 'costs_services', taxable: false },
    '518': { type: 'N', category: 'costs_services', taxable: true },
    '521': { type: 'N', category: 'costs_personnel', taxable: true },
    '522': { type: 'N', category: 'costs_personnel', taxable: true },
    '523': { type: 'N', category: 'costs_personnel', taxable: true },
    '524': { type: 'N', category: 'costs_personnel', taxable: true },
    '525': { type: 'N', category: 'costs_personnel', taxable: false },
    '526': { type: 'N', category: 'costs_personnel', taxable: false },
    '527': { type: 'N', category: 'costs_personnel', taxable: true },
    '528': { type: 'N', category: 'costs_personnel', taxable: false },
    '531': { type: 'N', category: 'costs_taxes_fees', taxable: true },
    '532': { type: 'N', category: 'costs_taxes_fees', taxable: true },
    '538': { type: 'N', category: 'costs_taxes_fees', taxable: true },
    '541': { type: 'N', category: 'costs_other_operating', taxable: true },
    '542': { type: 'N', category: 'costs_other_operating', taxable: true },
    '543': { type: 'N', category: 'costs_other_operating', taxable: false },
    '544': { type: 'N', category: 'costs_other_operating', taxable: true },
    '545': { type: 'N', category: 'costs_other_operating', taxable: false },
    '546': { type: 'N', category: 'costs_other_operating', taxable: false },
    '547': { type: 'N', category: 'costs_other_operating', taxable: true },
    '548': { type: 'N', category: 'costs_other_operating', taxable: true },
    '549': { type: 'N', category: 'costs_other_operating', taxable: true },
    '551': { type: 'N', category: 'costs_depreciation_impairment', taxable: true },
    '553': { type: 'N', category: 'costs_depreciation_impairment', taxable: true },
    '555': { type: 'N', category: 'costs_depreciation_impairment', taxable: true },
    '557': { type: 'N', category: 'costs_depreciation_impairment', taxable: false },
    '561': { type: 'N', category: 'costs_financial', taxable: true },
    '562': { type: 'N', category: 'costs_financial', taxable: true },
    '563': { type: 'N', category: 'costs_financial', taxable: true },
    '564': { type: 'N', category: 'costs_financial', taxable: true },
    '565': { type: 'N', category: 'costs_financial', taxable: true },
    '566': { type: 'N', category: 'costs_financial', taxable: true },
    '567': { type: 'N', category: 'costs_financial', taxable: true },
    '568': { type: 'N', category: 'costs_financial', taxable: true },
    '569': { type: 'N', category: 'costs_financial', taxable: true },
    '579': { type: 'N', category: 'costs_financial', taxable: true },
    '591': { type: 'N', category: 'costs_income_tax', taxable: true },
    '592': { type: 'N', category: 'costs_income_tax', taxable: true },
    '595': { type: 'N', category: 'costs_income_tax', taxable: false },
    '596': { type: 'N', category: 'costs_transfer_accounts', taxable: false },
    '601': { type: 'VYN', category: 'revenue_sales', taxable: true },
    '602': { type: 'VYN', category: 'revenue_sales', taxable: true },
    '604': { type: 'VYN', category: 'revenue_sales', taxable: true },
    '606': { type: 'VYN', category: 'revenue_sales', taxable: true },
    '607': { type: 'VYN', category: 'revenue_sales', taxable: true },
    '611': { type: 'VYN', category: 'revenue_stock_changes', taxable: true },
    '612': { type: 'VYN', category: 'revenue_stock_changes', taxable: true },
    '613': { type: 'VYN', category: 'revenue_stock_changes', taxable: true },
    '614': { type: 'VYN', category: 'revenue_stock_changes', taxable: true },
    '621': { type: 'VYN', category: 'revenue_activation', taxable: true },
    '622': { type: 'VYN', category: 'revenue_activation', taxable: true },
    '623': { type: 'VYN', category: 'revenue_activation', taxable: true },
    '624': { type: 'VYN', category: 'revenue_activation', taxable: true },
    '641': { type: 'VYN', category: 'revenue_other_operating', taxable: true },
    '642': { type: 'VYN', category: 'revenue_other_operating', taxable: true },
    '644': { type: 'VYN', category: 'revenue_other_operating', taxable: true },
    '645': { type: 'VYN', category: 'revenue_other_operating', taxable: false },
    '646': { type: 'VYN', category: 'revenue_other_operating', taxable: true },
    '648': { type: 'VYN', category: 'revenue_other_operating', taxable: true },
    '649': { type: 'VYN', category: 'revenue_other_operating', taxable: true },
    '655': { type: 'VYN', category: 'revenue_corrections_reversals', taxable: true },
    '657': { type: 'VYN', category: 'revenue_corrections_reversals', taxable: true },
    '661': { type: 'VYN', category: 'revenue_financial', taxable: true },
    '662': { type: 'VYN', category: 'revenue_financial', taxable: true },
    '663': { type: 'VYN', category: 'revenue_financial', taxable: true },
    '664': { type: 'VYN', category: 'revenue_financial', taxable: true },
    '665': { type: 'VYN', category: 'revenue_financial', taxable: true },
    '666': { type: 'VYN', category: 'revenue_financial', taxable: true },
    '667': { type: 'VYN', category: 'revenue_financial', taxable: true },
    '668': { type: 'VYN', category: 'revenue_financial', taxable: true },
    '692': { type: 'VYN', category: 'revenue_subsidies', taxable: true },
    '693': { type: 'VYN', category: 'revenue_subsidies', taxable: true },
    '694': { type: 'VYN', category: 'revenue_subsidies', taxable: true },
    '701': { type: 'Z', category: 'closing_accounts' },
    '702': { type: 'Z', category: 'closing_accounts' },
    '710': { type: 'Z', category: 'closing_accounts' },
    '711': { type: 'Z', category: 'closing_accounts' }
};
